TOKEN = "5633146247:AAGppS_-l-pKkxiq_goCs9-Wme7WaZWF6ik"
loggingFormat = {
    'A': '%(asctime)s -- %(filename)s --> Function: %(funcName)s() --> Line: %(lineno)s -- %(levelname)s -- Message: %(message)s',
}
cities = {
    'تهران' : {
        'id' : 1,
        'title' : 'Tehran',
        'name' : 'تهران',
        'airport' : 'مهرآباد',
        'airportCode' : 'THR',
        'timezone' : 'Asia/Tehran',
        'timezoneOffsetStr' : '+03:30',
        'type' : {
            'domestic' : True,
            'domesticId' : 1,
            'international' : True,
            'internationalId' : 1,
        }
    },
    'مشهد' : {
        'id' : 2,
        'title' : 'Mashhad',
        'name' : 'مشهد',
        'airport' : 'هاشمی نژاد مشهد',
        'airportCode' : 'MHD',
        'timezone' : 'Asia/Tehran',
        'timezoneOffsetStr' : '+03:30',
        'type' : {
            'domestic' : True,
            'domesticId' : 2,
            'international' : True,
            'internationalId' : 2,
        }
    },
    'کیش' : {
        'id' : 3,
        'title' : 'Kish',
        'name' : 'کیش',
        'airport' : 'مهرآباد',
        'airportCode' : 'KIH',
        'timezone' : 'Asia/Tehran',
        'timezoneOffsetStr' : '+03:30',
        'type': {
            'domestic': True,
            'domesticId': 3,
            'international': True,
            'internationalId': 10,
        }
    },
    'اهواز' : {
        'id': 4,
        'title' : 'Ahwaz',
        'name': 'اهواز',
        'airport': 'مهرآباد',
        'airportCode': 'KIH',
        'timezone': 'Asia/Tehran',
        'timezoneOffsetStr': '+03:30',
        'type': {
            'domestic': True,
            'domesticId': 4,
            'international': True,
            'internationalId': 3,
        }
    },
    'اصفهان' : {
        'id': 5,
        'title' : 'Isfahan',
        'name': 'اصفهان',
        'airport': 'مهرآباد',
        'airportCode': 'KIH',
        'timezone': 'Asia/Tehran',
        'timezoneOffsetStr': '+03:30',
        'type': {
            'domestic': True,
            'domesticId': 5,
            'international': True,
            'internationalId': 4,
        }
    },
    'شیراز' : {
        'id': 6,
        'title' : 'Shiraz',
        'name': 'شیراز',
        'airport': 'مهرآباد',
        'airportCode': 'KIH',
        'timezone': 'Asia/Tehran',
        'timezoneOffsetStr': '+03:30',
        'type': {
            'domestic': True,
            'domesticId': 6,
            'international': True,
            'internationalId': 5,
        }
    },
    'مسقط' : {
        'id': 7,
        'title' : 'Muscat',
        'name': 'مسقط',
        'airport': 'مهرآباد',
        'airportCode': 'KIH',
        'timezone': 'Asia/Muscat',
        'timezoneOffsetStr': '+04:00',
    },
    'قشم' : {
        'id': 8,
        'title' : 'Gheshm',
        'name': 'قشم',
        'airport': 'مهرآباد',
        'airportCode': 'KIH',
        'timezone': 'Asia/Tehran',
        'timezoneOffsetStr': '+03:30',
    },
    'تبریز' : {
        'id': 9,
        'title' : 'Tabriz',
        'name': 'تبریز',
        'airport': 'مهرآباد',
        'airportCode': 'KIH',
        'timezone': 'Asia/Tehran',
        'timezoneOffsetStr': '+03:30',
    },
    'بندرعباس' : {
        'id': 10,
        'title': 'Bandar%20Abass',
        'name': 'بندرعباس',
        'airport': 'مهرآباد',
        'airportCode': 'KIH',
        'timezone': 'Asia/Tehran',
        'timezoneOffsetStr': '+03:30',
    },
    # 11: 'Yerevan',
    # 12: 'Istanbul_Sabiha',
    # 13: 'Istanbul',
    # 14: 'Antalya',
    # 15: 'Tbilisi',
    # 16: 'Dubai_Sharjeh',
    # 17: 'Kerman',
    # 18: 'Izmir',
    # 19: 'Najaf',
    # 20: 'Batumi',
    # 21: 'Zahedan',
    # 22: 'Gorgan',
    # 23: 'Moscow_Sheremetyevo',
    # 24: 'Bushehr',
    # 25: 'Dalaman',
    # 26: 'Abadan',
    # 27: 'Antalya_Denizli',
    # 28: 'Urmia',
    # 29: 'Rimini_Italy',
    # 30: 'Chahbahar',
    # 31: 'Asalooye',
    # 32: 'Yazd',
    # 33: 'Erbil',
    # 34: 'Ardabil',
    # 35: 'Ankara',
    # 36: 'Sulaymaniyah',
    # 37: 'Ilam',
    # 38: 'Kermanshah',
    # 39: 'Almaty',
    # 40: 'Moscow_Vnukovo',
    # 41: 'Dezful',
    # 42: 'DELHI',
    # 43: 'Alanya',
    # 44: 'Khoramabad',
    # 45: 'Bodrum_Kusadasi',
    # 46: 'Bangkok',
    # 47: 'Shahrekord',
    # 48: 'Sari',
    # 49: 'Varna',
    # 50: 'Zabol',
    # 51: 'Lahore',
    # 52: 'Mumbai',
    # 53: 'Antalya_Isparta',
    # 54: 'Baghdad',
    # 55: 'Tabas',
    # 56: 'Bam',
    # 57: 'Beirut',
    # 58: 'Gheshm',
    # 59: 'Ramsar',
    # 60: 'Sabzevar',
    # 61: 'Frankfurt',
    # 62: 'BandarLenge',
    # 63: 'Sanandaj',
    # 64: 'Lar',
    # 65: 'Karachi',
    # 66: 'Yasooj',
    # 67: 'Hamburg',
    # 68: 'Tashkent',
    # 69: 'Syrjan',
    # 70: 'Maragheh',
    # 71: 'Dushanbe',
    # 72: 'Iranshar',
    # 73: 'Bojnourd',
    # 74: 'Kish',
    # 75: 'Paris',
    # 76: 'Jahrom',
    # 77: 'Rafsanjan',
    # 78: 'Jiroft',
    # 79: 'Vienna',
    # 80: 'Guangzhou',
    # 81: 'PARSABAD%20Moghan',
    # 82: 'Jask',
    # 83: 'BAKU',
}

flightsCommision = {
    'اکونومی': 0.05,
    'سیستمی': 0.07,
    'بیزینس': 0.09,
}
channelsIDs = {
    "Parvaz_charters" : -1001882499515,
}